"use client";

import { useEffect, useRef } from "react";

const CLOUDINARY_MP4 =
  "https://res.cloudinary.com/jobsway/video/upload/v1788892806/vcl_icrnm8.mp4";
// Poster frame generated by Cloudinary (frame at ~1s)
const CLOUDINARY_POSTER =
  "https://res.cloudinary.com/jobsway/video/upload/so_1/v1788892806/vcl_icrnm8.jpg";

const PLAYBACK_RATE = 2;

export default function HeroVideo() {
  const videoRef = useRef<HTMLVideoElement>(null);

  // Keep the rate pinned at 2x (browsers can reset it on load/play).
  const applyRate = () => {
    const v = videoRef.current;
    if (v) v.playbackRate = PLAYBACK_RATE;
  };

  // Set on mount too — metadata may load before React attaches the handlers.
  useEffect(() => {
    applyRate();
  }, []);

  return (
    <div className="relative aspect-video w-full overflow-hidden rounded-xl border border-neutral-300 bg-neutral-900">
      <video
        ref={videoRef}
        className="h-full w-full object-cover"
        src={CLOUDINARY_MP4}
        poster={CLOUDINARY_POSTER}
        controls
        playsInline
        preload="metadata"
        onLoadedMetadata={applyRate}
        onPlay={applyRate}
      />
    </div>
  );
}
